In [1]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive


In [24]:
import pandas as pd

df = pd.read_csv('/content/drive/MyDrive/codeReview/3_preprocessing/preprocessedData.csv')
df.head()

description  Personal attacks  \
0          it may hapen service diea service may die                 0   
1  zhiyan thanks helping explanation overal corec...                 0   
2          code inline refactored put main main main                 0   
3  interupt handler cal wake up loks like ned thr...                 1   
4  sure leads color makes white leter readable ne...                 0   

   Threats or intimidation  Mockery  Lack of specificity  \
0                        0        0                    1   
1                        0        0                    0   
2                        0        0                    0   
3                        0        1                    1   
4                        0        0                    0   

   Discouragement without guide  Disregard for other time or boundaries  \
0                             0                                       0   
1                             0                                       0   
2                             0                                       0   
3                             0                                       1   
4                             0                                       0   

   Unconscious bias  Dismissive attitude  Excessive control  Social  Toxic  \
0                 0                    0                  0       0      0   
1                 0                    0                  0       1      0   
2                 0                    0                  0       1      0   
3                 0                    0                  0       0      0   
4                 0                    0                  0       1      0   

   AntiSocial  NonToxic  
0           1         1  
1           0         1  
2           0         1  
3           1         1  
4           0         1

In [34]:
from sklearn.metrics import accuracy_score, classification_report

def evaluate_model(y_pred, y_test, model_name):
  accuracy = accuracy_score(y_test, y_pred)
  print(f'Accuracy {model_name}: {accuracy:.2f}')
  report = classification_report(y_test, y_pred)
  print(f'Classification Report of {model_name}:\n{report}')

In [35]:
def train_model(model, model_name, X_train, X_test, y_train, y_test):
  model.fit(X_train, y_train)
  y_pred=model.predict(X_test)
  evaluate_model(y_pred, y_test, model_name)

In [36]:
from sklearn.tree import DecisionTreeClassifier
from sklearn.svm import SVC
from xgboost import XGBClassifier
from sklearn.neural_network import MLPClassifier
from sklearn.naive_bayes import GaussianNB
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import  LSTM, Dense

LSTM = Sequential([
    LSTM(units=100),
    Dense(1, activation='sigmoid')  # for binary classification
])


def implement_models(X_train, X_test, y_train, y_test):
  train_model(DecisionTreeClassifier(), 'DecisionTree', X_train, X_test, y_train, y_test)
  train_model(SVC(), 'SVD', X_train, X_test, y_train, y_test)
  train_model(GaussianNB(), 'Naive Bayes', X_train, X_test, y_train, y_test)
  train_model(XGBClassifier(), 'XGBOOST', X_train, X_test, y_train, y_test)
  train_model(MLPClassifier(), 'MLP', X_train, X_test, y_train, y_test)
  train_model(LSTM(), 'LSTM', X_train, X_test, y_train, y_test)


In [ ]:
from sklearn.model_selection import train_test_split

# Model Training
# Load BoW representation from the saved file
csv_file_path = '/content/drive/MyDrive/codeReview/4_wordVectorization/bow_representation.csv'
loaded_bow_representation = pd.read_csv(csv_file_path)

# Combine the loaded BoW representation with the labels
X = loaded_bow_representation
y = df['Personal attacks']

# Split the data into training and testing sets
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

In [ ]:
print('implement models for BoW representation')
implement_models(X_train, X_test, y_train, y_test)

implement models for BoW representation
Accuracy DecisionTree: 0.54
Classification Report of DecisionTree:
              precision    recall  f1-score   support

           0       0.62      0.31      0.42        32
           1       0.51      0.79      0.62        29

    accuracy                           0.54        61
   macro avg       0.57      0.55      0.52        61
weighted avg       0.57      0.54      0.51        61

Accuracy SVD: 0.51
Classification Report of SVD:
              precision    recall  f1-score   support

           0       1.00      0.06      0.12        32
           1       0.49      1.00      0.66        29

    accuracy                           0.51        61
   macro avg       0.75      0.53      0.39        61
weighted avg       0.76      0.51      0.38        61

Accuracy Naive Bayes: 0.56
Classification Report of Naive Bayes:
              precision    recall  f1-score   support

           0       0.56      0.75      0.64        32
           1    

In [ ]:
# Load TF_IDF representation from the saved file
csv_file_path = '/content/drive/MyDrive/codeReview/4_wordVectorization/tfidf_representation.csv'
loaded_tfidf_representation = pd.read_csv(csv_file_path)

# Combine the loaded TF_IDF representation with the labels
X = loaded_tfidf_representation
y = df['AntiSocial']

# Split the data into training and testing sets
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

In [ ]:
print('implement models for TF_IDF representation\n')
implement_models(X_train, X_test, y_train, y_test)

implement models for TF_IDF representation

Accuracy DecisionTree: 0.51
Classification Report of DecisionTree:
              precision    recall  f1-score   support

           0       0.57      0.25      0.35        32
           1       0.49      0.79      0.61        29

    accuracy                           0.51        61
   macro avg       0.53      0.52      0.48        61
weighted avg       0.53      0.51      0.47        61

Accuracy SVD: 0.52
Classification Report of SVD:
              precision    recall  f1-score   support

           0       1.00      0.09      0.17        32
           1       0.50      1.00      0.67        29

    accuracy                           0.52        61
   macro avg       0.75      0.55      0.42        61
weighted avg       0.76      0.52      0.41        61

Accuracy XGBOOST: 0.52
Classification Report of XGBOOST:
              precision    recall  f1-score   support

           0       0.59      0.31      0.41        32
           1       0

In [ ]:
# Load Word2Vec representation from the saved file
csv_file_path = '/content/drive/MyDrive/codeReview/4_wordVectorization/word2vec_representation.csv'
loaded_word2vec_representation = pd.read_csv(csv_file_path)

# Combine the loaded Word2Vec representation with the labels
X = loaded_word2vec_representation
y = df['AntiSocial']

# Split the data into training and testing sets
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

In [ ]:
print('implement models for Word2Vec representation\n')
implement_models(X_train, X_test, y_train, y_test)

implement models for Word2Vec representation

Accuracy DecisionTree: 0.66
Classification Report of DecisionTree:
              precision    recall  f1-score   support

           0       0.79      0.47      0.59        32
           1       0.60      0.86      0.70        29

    accuracy                           0.66        61
   macro avg       0.69      0.67      0.65        61
weighted avg       0.70      0.66      0.64        61

Accuracy SVD: 0.59
Classification Report of SVD:
              precision    recall  f1-score   support

           0       0.73      0.34      0.47        32
           1       0.54      0.86      0.67        29

    accuracy                           0.59        61
   macro avg       0.64      0.60      0.57        61
weighted avg       0.64      0.59      0.56        61

Accuracy XGBOOST: 0.61
Classification Report of XGBOOST:
              precision    recall  f1-score   support

           0       0.70      0.44      0.54        32
           1      

/usr/local/lib/python3.10/dist-packages/sklearn/metrics/_classification.py:1344: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/usr/local/lib/python3.10/dist-packages/sklearn/metrics/_classification.py:1344: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/usr/local/lib/python3.10/dist-packages/sklearn/metrics/_classification.py:1344: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))


In [ ]:
# Load Glove representation from the saved file
csv_file_path = '/content/drive/MyDrive/codeReview/4_wordVectorization/glove_representation.csv'
loaded_glove_representation = pd.read_csv(csv_file_path)

# Combine the loaded Glove representation with the labels
X = loaded_glove_representation
y = df['AntiSocial']

# Split the data into training and testing sets
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

In [ ]:
print('implement models for Glove representation\n')
implement_models(X_train, X_test, y_train, y_test)

implement models for Glove representation

Accuracy DecisionTree: 0.51
Classification Report of DecisionTree:
              precision    recall  f1-score   support

           0       0.54      0.44      0.48        32
           1       0.49      0.59      0.53        29

    accuracy                           0.51        61
   macro avg       0.51      0.51      0.51        61
weighted avg       0.51      0.51      0.51        61

Accuracy SVD: 0.56
Classification Report of SVD:
              precision    recall  f1-score   support

           0       0.86      0.19      0.31        32
           1       0.52      0.97      0.67        29

    accuracy                           0.56        61
   macro avg       0.69      0.58      0.49        61
weighted avg       0.70      0.56      0.48        61

Accuracy XGBOOST: 0.59
Classification Report of XGBOOST:
              precision    recall  f1-score   support

           0       0.65      0.47      0.55        32
           1       0.

/usr/local/lib/python3.10/dist-packages/sklearn/neural_network/_multilayer_perceptron.py:686: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(


In [ ]:
# Load FastText representation from the saved file
csv_file_path = '/content/drive/MyDrive/codeReview/4_wordVectorization/fasttext_representation.csv'
loaded_fasttext_representation = pd.read_csv(csv_file_path)

# Combine the loaded FastText representation with the labels
X = loaded_fasttext_representation
y = df['AntiSocial']

# Split the data into training and testing sets
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

In [ ]:
print('implement models for FastText representation\n')
implement_models(X_train, X_test, y_train, y_test)

implement models for FastText representation

Accuracy DecisionTree: 0.44
Classification Report of DecisionTree:
              precision    recall  f1-score   support

           0       0.46      0.41      0.43        32
           1       0.42      0.48      0.45        29

    accuracy                           0.44        61
   macro avg       0.44      0.44      0.44        61
weighted avg       0.45      0.44      0.44        61

Accuracy SVD: 0.49
Classification Report of SVD:
              precision    recall  f1-score   support

           0       1.00      0.03      0.06        32
           1       0.48      1.00      0.65        29

    accuracy                           0.49        61
   macro avg       0.74      0.52      0.36        61
weighted avg       0.75      0.49      0.34        61

Accuracy XGBOOST: 0.49
Classification Report of XGBOOST:
              precision    recall  f1-score   support

           0       0.52      0.41      0.46        32
           1      

/usr/local/lib/python3.10/dist-packages/sklearn/metrics/_classification.py:1344: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/usr/local/lib/python3.10/dist-packages/sklearn/metrics/_classification.py:1344: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/usr/local/lib/python3.10/dist-packages/sklearn/metrics/_classification.py:1344: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))


In [12]:
# Load USE representation from the saved file
csv_file_path = '/content/drive/MyDrive/codeReview/4_wordVectorization/use_representation.csv'
loaded_use_representation = pd.read_csv(csv_file_path)

# Combine the loaded USE representation with the labels
X = loaded_use_representation
y = df['AntiSocial']

# Split the data into training and testing sets
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

In [ ]:
print('implement models for USE representation\n')
implement_models(X_train, X_test, y_train, y_test)

implement models for USE representation

Accuracy DecisionTree: 0.66
Classification Report of DecisionTree:
              precision    recall  f1-score   support

           0       0.72      0.56      0.63        32
           1       0.61      0.76      0.68        29

    accuracy                           0.66        61
   macro avg       0.67      0.66      0.65        61
weighted avg       0.67      0.66      0.65        61

Accuracy SVD: 0.61
Classification Report of SVD:
              precision    recall  f1-score   support

           0       0.68      0.47      0.56        32
           1       0.56      0.76      0.65        29

    accuracy                           0.61        61
   macro avg       0.62      0.61      0.60        61
weighted avg       0.63      0.61      0.60        61

Accuracy XGBOOST: 0.54
Classification Report of XGBOOST:
              precision    recall  f1-score   support

           0       0.59      0.41      0.48        32
           1       0.51

/usr/local/lib/python3.10/dist-packages/sklearn/neural_network/_multilayer_perceptron.py:686: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(


In [14]:
# Load BERT representation from the saved file
csv_file_path = '/content/drive/MyDrive/codeReview/4_wordVectorization/bert_representation.csv'
loaded_bert_representation = pd.read_csv(csv_file_path)

# Combine the loaded BERT representation with the labels
X = loaded_bert_representation
y = df['AntiSocial']

# Split the data into training and testing sets
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

In [ ]:
print('implement models for BERT representation\n')
implement_models(X_train, X_test, y_train, y_test)

implement models for BERT representation

Accuracy DecisionTree: 0.59
Classification Report of DecisionTree:
              precision    recall  f1-score   support

           0       0.67      0.44      0.53        32
           1       0.55      0.76      0.64        29

    accuracy                           0.59        61
   macro avg       0.61      0.60      0.58        61
weighted avg       0.61      0.59      0.58        61

Accuracy SVD: 0.57
Classification Report of SVD:
              precision    recall  f1-score   support

           0       0.88      0.22      0.35        32
           1       0.53      0.97      0.68        29

    accuracy                           0.57        61
   macro avg       0.70      0.59      0.52        61
weighted avg       0.71      0.57      0.51        61

Accuracy XGBOOST: 0.61
Classification Report of XGBOOST:
              precision    recall  f1-score   support

           0       0.83      0.31      0.45        32
           1       0.5

/usr/local/lib/python3.10/dist-packages/sklearn/neural_network/_multilayer_perceptron.py:686: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(


In [17]:
import numpy as np
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from tensorflow.keras.preprocessing.text import Tokenizer
from tensorflow.keras.preprocessing.sequence import pad_sequences
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Embedding, GRU, Dense, Dropout


# Assuming 'comments' is the column with text comments
comments = df['description'].astype(str).values
labels = df['AntiSocial'].values

# Tokenize the comments
tokenizer = Tokenizer()
tokenizer.fit_on_texts(comments)
vocab_size = len(tokenizer.word_index) + 1

# Convert text to sequences
sequences = tokenizer.texts_to_sequences(comments)

# Pad sequences to have consistent length
max_length = 100
padded_sequences = pad_sequences(sequences, maxlen=max_length, padding='post')

# Split the data into training and testing sets
X_train, X_test, y_train, y_test = train_test_split(
    padded_sequences, labels, test_size=0.2, random_state=42
)

In [18]:
# Define the GRU model
model = Sequential()
model.add(Embedding(input_dim=vocab_size, output_dim=100, input_length=max_length))
model.add(GRU(units=64, activation='relu'))
model.add(Dense(64, activation='relu'))
model.add(Dropout(0.5))
model.add(Dense(1, activation='sigmoid'))

# Compile the model
model.compile(optimizer='adam', loss='binary_crossentropy', metrics=['accuracy'])

# Train the model
model.fit(X_train, y_train, epochs=5, batch_size=64, validation_split=0.2)

# Evaluate the model
loss, accuracy = model.evaluate(X_test, y_test)
print(f'Test Accuracy: {accuracy * 100:.2f}%')


Epoch 1/5
3/3 [==============================] - 2s 207ms/step - loss: 0.6921 - accuracy: 0.5625 - val_loss: 0.6899 - val_accuracy: 0.5625
Epoch 2/5
3/3 [==============================] - 0s 83ms/step - loss: 0.6862 - accuracy: 0.5990 - val_loss: 0.6881 - val_accuracy: 0.5625
Epoch 3/5
3/3 [==============================] - 0s 83ms/step - loss: 0.6829 - accuracy: 0.5938 - val_loss: 0.6865 - val_accuracy: 0.5625
Epoch 4/5
3/3 [==============================] - 0s 80ms/step - loss: 0.6806 - accuracy: 0.5990 - val_loss: 0.6857 - val_accuracy: 0.5625
Epoch 5/5
2/2 [==============================] - 0s 16ms/step - loss: 0.7066 - accuracy: 0.4754
Test Accuracy: 47.54%


In [26]:
import numpy as np
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score
from transformers import BertTokenizer, TFBertForSequenceClassification
from tensorflow.keras.optimizers import Adam
from tensorflow.keras.losses import BinaryCrossentropy
from tensorflow.keras.metrics import BinaryAccuracy
from tensorflow.keras.callbacks import EarlyStopping

# Assuming 'comments' is the column with text comments
comments = df['description'].astype(str).values
labels = df['AntiSocial'].values

# Split the data into training and testing sets
X_train, X_test, y_train, y_test = train_test_split(
    comments, labels, test_size=0.2, random_state=42
)

# Load BERT tokenizer and model
tokenizer = BertTokenizer.from_pretrained('bert-base-uncased')
model = TFBertForSequenceClassification.from_pretrained('bert-base-uncased')

# Tokenize the input data
X_train_tokens = [tokenizer.encode_plus(text, padding=True, truncation=True, return_tensors='tf', max_length=128) for text in X_train]
X_test_tokens = [tokenizer.encode_plus(text, padding=True, truncation=True, return_tensors='tf', max_length=128) for text in X_test]

# Convert BatchEncoding objects to tuples
X_train_tokens = [(token['input_ids'], token['token_type_ids'], token['attention_mask']) for token in X_train_tokens]
X_test_tokens = [(token['input_ids'], token['token_type_ids'], token['attention_mask']) for token in X_test_tokens]

All PyTorch model weights were used when initializing TFBertForSequenceClassification.

Some weights or buffers of the TF 2.0 model TFBertForSequenceClassification were not initialized from the PyTorch model and are newly initialized: ['classifier.weight', 'classifier.bias']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.


In [29]:
X_train_tokens[50]

(<tf.Tensor: shape=(1, 63), dtype=int32, numpy=
 array([[  101,  4365,  2157,  9530, 13473,  2595, 18098, 21318,  3372,
         16703,  1056, 21677, 19231,  7629, 28139,  8873,  2595, 21318,
          3372, 16703,  1056,  1043,  2385, 21318,  3372, 16703,  1056,
          1048,  1022, 21318,  3372, 16703,  1056, 21318,  3372, 16703,
          1056, 17576, 27788,  3334, 28139,  2102,  3459, 21318,  3372,
         16703,  1056,  2171,  2278,  2358,  2099,  3415,  4697,  1018,
         17576,  1022, 21677, 19231,  7629, 28139,  8873,  2595,   102]],
       dtype=int32)>,
 <tf.Tensor: shape=(1, 63), dtype=int32, numpy=
 array([[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
         0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
         0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]],
       dtype=int32)>,
 <tf.Tensor: shape=(1, 63), dtype=int32, numpy=
 array([[1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
         1, 1

In [32]:
print("Number of training samples:", len(X_train), len(X_train_tokens))

Number of training samples: 240 240


In [33]:
print(np.array(X_train_tokens).shape)
print(np.array(y_train).shape)


<ipython-input-33-154be61a640a>:1: VisibleDeprecationWarning: Creating an ndarray from ragged nested sequences (which is a list-or-tuple of lists-or-tuples-or ndarrays with different lengths or shapes) is deprecated. If you meant to do this, you must specify 'dtype=object' when creating the ndarray.
  print(np.array(X_train_tokens).shape)


ValueError: ignored

In [30]:
# Define the model
model.compile(optimizer=Adam(learning_rate=2e-5),
              loss=BinaryCrossentropy(),
              metrics=[BinaryAccuracy()])


# Early stopping to prevent overfitting
early_stopping = EarlyStopping(monitor='val_loss', patience=3, restore_best_weights=True)

# Train the model
model.fit(X_train_tokens, y_train, validation_split=0.1, epochs=5, batch_size=32, callbacks=[early_stopping])

# Evaluate the model
predictions = model.predict(X_test_tokens)['logits']
predicted_labels = np.argmax(predictions, axis=1)
test_accuracy = accuracy_score(y_test, predicted_labels)

print(f'Test Accuracy: {test_accuracy * 100:.2f}%')

ValueError: ignored